### ISSUE TITLE
Text is blank on iOS Safari/chrome

### ISSUE THREAD

**Issue by refazi** [ibz/lightning-shell#2]
When using mobile browser like safari or chrome in iOS, the text is blank -  looks like the characters are colored the same as the background.

**Comment by AaronDewes** [comment]
What versionn are you using? Buster (Umbrel) or Bullseye (Citadel)?

**Comment by refazi** [comment]
Citadel

**Comment by ibz** [comment]
Could be related to this: https://github.com/tsl0922/ttyd/issues/798

What iOS version are you using?

**Comment by ibz** [comment]
It's been over a year since `ttyd` released a new version. Others are also asking for a new release https://github.com/tsl0922/ttyd/issues/784

I could try building it from master, though I don't really like that approach.

What do you think, @AaronDewes ?

**Comment by AaronDewes** [comment]
That would mean reverting some changes for bullseye in `generate-dockerfile.sh`, but it sounds like a good idea.

**Comment by ibz** [comment]
Hey @AaronDewes, I've made a new build with the last ttyd (on master). Could you try it on Citadel and confirm that the issue is fixed? If so, I will create a new tag and close the issue.

**Comment by AaronDewes** [comment]
I've published the new version to Citadel, but can't test it myself, @refazi it'd be great if you could try with the update apps button and waiting a few minutes.

**Comment by refazi** [comment]
I updated twice, the version in the App Store shows as 1.1.1, still have the same issue.

**Comment by AaronDewes** [comment]
Can you try to SSH in and run `~/citadel/events/triggers/app-update`

**Comment by ibz** [comment]
@AaronDewes is the SHA256 in app.yaml the correct one though? I am trying to run that container on my Umbrel and can't.

This one, I mean https://github.com/runcitadel/apps/commit/edf35a0efd18807693d4e10ca25deafc2149e5b9

**Comment by AaronDewes** [comment]
Thanks, that was the problem. Looks like I had another sha256 copied and pasted that by accident

**Comment by refazi** [comment]
The app doesn’t seem to start, the docker log on syslog says “manifest unknown”

**Comment by ibz** [comment]
I think this is getting a bit confusing now, with so many versions flying around. I've created version 0.1.3 of lightning-shell and submitted a pull request to @runcitadel. Ideally we will be using tagged versions, not builds from master.

**Comment by refazi** [comment]
I still see an issue, the COI toner in version 0.1.3 doesn’t come up, I see the following error on the container log:
Standard_init_linux.go:228: exec user process caused exec format error

**Comment by ibz** [comment]
Hmm, that is strange, that error should show up when you try to run a container built for the wrong architecture - like running the amd64 container on the Pi.

But the SHA in https://github.com/runcitadel/apps/blob/main/apps/lightning-shell/app.yml matches the SHA of the ARM64 build on https://github.com/ibz/lightning-shell/pkgs/container/lightning-shell/13252298?tag=v0.1.3-bullseye-slim .

Is there any other place where you are storing the image reference/SHA, @AaronDewes ? Or can it be that he did not update to the last yml?

Or ... are you running Citadel on something else than Raspberry Pi @refazi ?

Other than that, I don't understand how this would happen.

**Comment by refazi** [comment]
Yeah it’s running on x86, can you build it for that arch as well?

**Comment by ibz** [comment]
Yeah, v0.1.3 was built for x86 as well, but I wrongly added the SHA256 of the ARCH build (thinking Citadel is only used on Raspberry Pi, silly me).

I think @AaronDewes fixed it by now.

**Comment by AaronDewes** [comment]
I fixed it, but even after my PR to add a missing dependency, it's still broken. I'll debug it further

**Comment by refazi** [comment]
Btw I just installed the umbrel version via the umbrel 0.4.11 release and I have the same issue

**Comment by ibz** [comment]
Yes, Umbrel has the old version. I submitted to them before the fix. :)

**Comment by ibz** [comment]
@AaronDewes I just had a look at your app.yaml, it seems like you are using a build from master, that may be broken (master is sometimes broken).

You should be using v0.1.3, which works fine on my Umbrel.

**Comment by ibz** [comment]
Ha! I found something...

I think it's only the Bullseye image that is broken (`libwebsockets` fails to load `evlib_uv` for some reason) whereas the Buster image works fine. Hence it worked for me on Umbrel (using Buster).

I'll investigate further and come up with a fix, but before that, to summarize...

* Using the version currently on Umbrel (0.1.1) will work, but iOS will be broken.
* Using 0.1.3 *should* fix iOS (in theory - I did not test it yet) - but this build is broken on Bullseye and the Buster build not released on Umbrel yet.

As a temporary fix:

* on Umbrel, you could upgrade to 0.1.3 (Buster) by manually editing app.yaml and relaunching.
* on Citadel - could we try to run 0.1.3 Buster rather than Bullseye?

**Comment by AaronDewes** [comment]
Sure, I'll try to go back to buster.

**Comment by ibz** [comment]
@AaronDewes I think the issue was this after all https://github.com/ibz/lightning-shell/commit/4c53e0986d7d2356f6edd717904bf0754b38ebf6#diff-5be359434de5b83c3988bbf1494c1dab5bb8110cf7141650fec0e06e02d4b1dcR102

Should be fixed now in master. I'll make a tag soon also.

**Comment by ibz** [comment]
BTW, v0.1.4 is released. I just submitted it to Umbrel. Could we add that to Citadel as well?

**Comment by refazi** [comment]
Updated to citadel 0.5.20 and 0.1.4 seems to be there.
The app loads and the browser experience is great, but I still have the same issue with the mobile browsers via iOS

**Comment by ibz** [comment]
@refazi Thanks for double checking! Too bad... OK, we'll leave this issue open then for now.

**Comment by editwentyone** [comment]
this is still an open bug on safari iOS or macOS with lightning shell 1.1.0 on citadel 0.0.2

the guys over at unraid.com had also such an visual bug with the terminal shell, but I couldn't find how they fixed it. all I can tell is, its working there.

<img width="1075" alt="Bildschirmfoto 2022-05-09 um 13 34 41" src="https://user-images.githubusercontent.com/96262473/167402094-f99315ac-9f9e-4b32-9185-5dcbc4feda80.png">
